<?php
    ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>CRUD Operations Using PHP, MySQL and Require.js</title>

        <!-- Bootstrap CSS File  -->
        <link rel="stylesheet" type="text/css" href="styles/bootstrap/css/bootstrap.css"/>
    </head>
    <body>

        <!-- Content Section -->
        <div class="container">
            <div class="row">
                <div class="col-md-4 product" style="padding-top: 2%;">

                    <form name="product-form" class="product-form" action="javascript:void(0);">
                        <div class="form-group">
                            <label for="email"><span style="color: red;font-weight: bold;">*</span> File Name : </label>
                            <input type="text" class="form-control" id="art-file-name" name="art-file-name" placeholder="Enter File Name">
                        </div>
                        <div class="form-group">
                            <label for="email"><span style="color: red;font-weight: bold;">*</span> Choose File : </label>
                            <input type="file" class="form-control" id="upload-file" name="product-name[]" multiple="multiple" >
                        </div>
                    </form>
                </div>
            </div>
            <div class="row product-list" style="display: none;" id="product-list-main-div">
                <div class="col-md-12">
                    <h3>File Details:</h3>

                    <div id="product-list-dv" class="records_content">

                    </div>
                </div>
            </div>
        </div>
        <!-- /Content Section -->


        <script type="text/javascript">
            var baseUrl = "<?php echo $base_url; ?>";
            var require = {
                urlArgs : "bust="+new Date().getTime()
            };
        </script>
        <script data-main="scripts/app" src="scripts/require.js"></script>
    </body>
</html>